### ISSUE TITLE
Fail after Repeater is handled

### ISSUE THREAD

**Issue by EllenFawkes** [EllenFawkes/PurrplingBot#95]
**Plugin: Announcer**

~Repeater queue lengght is 0, but expected is 1, because at 15:09 should be handled announce, but should be added to repeater queue, because inactivity on channel at 15:30~

*25% of 1 hour is 15 minutes. 1h announce may be handled 15:09 can be repeated max at 15:24 after channel activity detected.* **RESOLVED!**

```
[10.09.2017 15:30:57.258] [INFO]  <Announcer:Repeater> Processing announces queue for repeat ...
[10.09.2017 15:30:57.259] [INFO]  <Announcer:Repeater> Repeater started! Announces in queue:  0
[10.09.2017 15:32:04.044] [INFO]  <Storage> Data saved! File: config/storedb.json
npm info lifecycle purrplingbot@1.3.0-beta2~poststart: purrplingbot@1.3.0-beta2
npm info ok
/opt/PurrplingBot/plugins/Announcer/repeater.js:69
      this._logger.info("Repeater DONE! Queue is clear! ");
                  ^

TypeError: Cannot read property 'info' of undefined
    at Timeout._repeatAnnounce [as _onTimeout] (/opt/PurrplingBot/plugins/Announcer/repeater.js:69:19)
    at ontimeout (timers.js:473:15)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.2.1
npm info lifecycle purrplingbot@1.3.0-beta2~prestart: purrplingbot@1.3.0-beta2
npm info lifecycle purrplingbot@1.3.0-beta2~start: purrplingbot@1.3.0-beta2

> purrplingbot@1.3.0-beta2 start /opt/PurrplingBot
> node purrplingbot.js 2>&1 3>&1 | tee -a purrplingbot.log
```

What I am lost a _logger? It's not logical!

**Comment by EllenFawkes** [comment]
**Resolved!** It will be in 1.3.0-beta3. In beta 2 **disable Repeater!**
